
    create table acc_account (
        Isauxiliary boolean not null,
        Openingbalance numeric(15,2),
        Createdat timestamp(6) not null,
        Id bigint generated by default as identity,
        Parentid bigint,
        Updatedat timestamp(6),
        Code varchar(25) not null,
        Createdby varchar(100) not null,
        Updatedby varchar(100),
        TypeAccount varchar(255) not null check (TypeAccount in ('ASSET','LIABILITY','EXPENSE','INCOME')),
        primary key (Id),
        constraint ix_acc_account_code unique (code)
    );

    create table acc_currency (
        Purchaserate numeric(18,3) not null,
        Referencerate numeric(18,3) not null,
        Salesrate numeric(18,3) not null,
        Subunit integer,
        Unit integer,
        Createdat timestamp(6) not null,
        Id bigint generated by default as identity,
        Updatedat timestamp(6),
        Code varchar(25) not null,
        Description varchar(50) not null,
        Name varchar(50) not null,
        Createdby varchar(100) not null,
        Updatedby varchar(100),
        primary key (Id),
        constraint ix_acc_currency_code unique (code)
    );

    create table acc_vat (
        Rate numeric(10,7) not null,
        Createdat timestamp(6) not null,
        Id bigint generated by default as identity,
        Purchaseaccountid bigint not null,
        Salesaccountid bigint not null,
        updatedat timestamp(6),
        Code varchar(25) not null,
        Createdby varchar(100) not null,
        Updatedby varchar(100),
        primary key (Id),
        constraint ix_acc_vat_code unique (code)
    );

    alter table if exists acc_account 
       add constraint fk_acc_account_parent 
       foreign key (Parentid) 
       references acc_account;

    alter table if exists acc_vat 
       add constraint fk_acc_vat_purchaseaccount 
       foreign key (Purchaseaccountid) 
       references acc_account;

    alter table if exists acc_vat 
       add constraint fk_acc_vat_salesaccount 
       foreign key (Salesaccountid) 
       references acc_account;
